/* ============ EPILOGHI PERSONALI, IMPRESE E CRONACHE — PANDATARIA ============

   Consumato da engine.js → renderEnding():
     HERO_EPILOGUES[heroId][chiave] → STRINGA di HTML (mai una funzione: il motore
       la inserisce così com'è, vedi engine.js dentro renderEnding)
     CRONACA → righe di mondo, mostrate solo se G.flags[flag] è vero (serve `icon`)
     IMPRESE → achievement di fine partita, sbloccate da G.flags[flag]

   Le chiavi le decide engine.js dal PREFISSO dell'id della scena finale, così
   aggiungere una coda non richiede di toccare né lui né questo file:
     e_vittoria → e_vittoria_barca → e_vittoria_casa / e_vittoria_tacere ...... 'vittoria'
     e_vittoria_muta → e_muta_tramonto / e_muta_foto ......................... 'muta'
     e_scambio → e_scambio_ancora / e_scambio_barca → e_scambio_torna ........ 'scambio'
     e_resta → e_resta_partenza / e_resta_inverno ........................... 'resta'
     e_coro  (e_coro_insieme / e_coro_soli) ................. NESSUN epilogo (null)
     e_loop  (e_loop_differenza / e_loop_letto) ............. NESSUN epilogo (null)
   Nei due finali in cui il Coro vince gli eroi non hanno un "dopo" da raccontare e
   il silenzio è il punto: per questo qui NON esistono le chiavi 'coro' e 'loop'.
   Se un giorno il motore le riabilitasse, andrebbero scritte — non prima.

   REGOLA DI FERRO: ogni `flag` citato qui sotto deve essere impostato davvero da
   una scena (`sets:` nei drafts), o essere il flag di una ricetta / il premio di un
   mistero in drafts/campaign-header.js. Altrimenti tests/validate.mjs fallisce, e
   giustamente: un'impresa che non può scattare è una bugia detta al giocatore.

   In 'scambio' e in 'resta' CHI è rimasto giù (o sull'isola) lo decide il giocatore:
   questi testi non lo nominano MAI e devono funzionare per qualunque scelta — vale
   anche per e_resta_inverno, dove non parte nessuno dei due. */

const HERO_EPILOGUES = {

  gaetano: {
    vittoria: `Rientra in ufficio il 2 settembre e nella cartella dei progetti compare una sottocartella che non c'entra niente con i satelliti: <b>PANDATARIA</b>. Dentro ci sono tre nomi, una batimetrica scaricata da un portale del Ministero, undici secondi di riverbero e un conto che torna. Non la mostra a nessuno e non la cancella. Ha smesso di dire «sarà un motore»: quando un collega racconta una cosa senza spiegazione, Gaetano prende un foglio e chiede l'ora esatta. E il 2 settembre di ogni anno, alle due di notte, dice a voce alta una frase che nessuno gli ha chiesto di dire: «Sono le due, Nicola. Tutto regolare.» Poi chiude il quaderno e va a dormire, accanto a sua moglie, che respira.`,
    muta: `Ha comprato un idrofono vero a novembre, quattrocentoventi euro, e ha imparato a leggere gli spettrogrammi come si impara una lingua. Ha scritto a due professori di acustica: uno non ha risposto, l'altro sì, gentilissimo — <i>«molto probabilmente un diesel a bassi giri, riflesso dal fondale. Cordialmente.»</i> Gaetano ha stampato quella mail e l'ha messa nella cartella, perché una risposta sbagliata è comunque un dato. Da allora misura tutto quello che gli capita a tiro, e ogni tanto qualcuno in ufficio glielo fa notare ridendo. Ride pure lui. Poi, la sera, riapre il file: undici secondi di riverbero in una stanza di trenta metri. Il conto non torna. Non tornerà mai.`,
    scambio: `Il conto lo ha rifatto quattrocento volte, e ogni volta torna allo stesso modo: a quaranta metri, quel giorno, l'aria per due non c'era. È l'unica cosa che sa con certezza di quei due secondi, e non gli serve a niente. Del 30 agosto 2026 restano un biglietto della corsa che una macchinetta alla biglietteria di Cala Rossano continuerà a stampare ogni volta che qualcuno digita quel nome, e un quaderno di carta con tre nomi in fila e la grafia che si stringe verso il fondo pagina. Laggiù non ha deciso il coraggio: ha deciso un numero, e il numero era giusto. Gaetano lo sa. E ha cominciato a lavorare — piano, ostinato, senza dirlo a nessuno — sull'unica domanda che gli interessa ancora: <i>come si richiama indietro una voce.</i>`,
    resta: `Ha portato sull'isola un sismografo usato comprato da un rigattiere di Formia, e chi sta nella stanza a mese lo tiene in cantina e ogni mattina alle sette scarica dodici ore di niente: è il niente che tiene in piedi tutto il resto. Gaetano ha imparato gli orari del traghetto d'inverno a memoria come una preghiera — quando salta, quando non parte, quali giorni arriva il pane — e ha smesso di chiamare «coincidenza» le cose che non ha misurato. Alle otto di ogni sera si dicono cosa hanno mangiato: è una regola, e le regole reggono. Non era la vita che aveva progettato. La progetta adesso, giorno per giorno, e in questo lui è il migliore che ci sia.`,
  },

  claudia: {
    vittoria: `Non ha pubblicato niente. Dieci anni a decidere come le cose vengono viste, e la storia più grossa che le sia capitata sta in una cartella privata che non ha nemmeno un titolo, solo una data. Ha un mestiere nuovo dentro il mestiere vecchio: quando qualcuno le racconta una cosa che nessuno gli crede, Claudia non dice «avrai sentito male». Chiede l'ora, chiede il posto, e la scrive. Torna a Ventotene il 27 agosto dell'anno dopo, e di quello dopo. Arriva alla boa ogni volta, e ogni volta ci resta appesa un minuto in più — non per sfida: perché <b>ascolta</b>, e il niente che sente adesso è il risultato di una cosa che ha fatto lei. Alle sette di sera, a Cala Rossano, entra in acqua fino alla vita e dice piano una frase sulle gambe che vanno tenute dietro e non sotto.`,
    muta: `Ha diecimila immagini perfette per lavoro e quattromiladuecento file dentro una cartella che si chiama VENTOTENE, e nessuno di quei file risponde alla domanda. Ha imparato a zoomare sul bordo dell'inquadratura prima che sul soggetto, che è un vizio da montatrice e adesso è qualcos'altro. Ogni anno, sul ponte di poppa, con lo stesso vento, dice la stessa frase — <i>«era qualcosa»</i> — e ogni anno qualcuno le risponde <i>«era qualcosa»</i>, e non è poco. Una volta, in cucina, Ada ha cominciato una frase con «mia sorella» e poi si è girata verso il lavello. Claudia non l'ha ripresa. Ci pensa spesso. Non sa che era quella, la porta.`,
    scambio: `Ha smesso di fotografare per otto mesi. Poi ha ricominciato da una cosa sola: il mare, sempre la stessa inquadratura, sempre alla stessa ora, duemila scatti in cui non c'è la banda. In nessuno. Alla Terrazza di Mimì, dal quindicesimo anno, il cameriere porta due limoncelli e ne posa uno davanti alla sedia che non si sposta: l'ha cominciato da solo, senza chiedere niente a nessuno. E la cosa che Claudia sa e non dice mai è questa: a quaranta metri, in due secondi, la decisione l'ha presa qualcuno che aveva paura dell'acqua profonda da tutta la vita e ha scelto comunque. Chi ha paura e scende lo stesso canta in un modo che nessuno aveva mai avuto. Adesso quel timbro esiste, ed è di questa storia.`,
    resta: `La promessa era sua, ed era la cosa più piccola e più vera che ci fosse da dire: <i>«Ha sei anni e sta in un posto dove non si tocca. Le ho detto che le insegno a nuotare. L'ho detto io, con la mia voce, e quella ci ha creduto.»</i> Adesso quella promessa ha un orario. Alle sette di ogni mattina, a Cala Rossano, dove si tocca, qualcuno entra in acqua fino alla vita e parla con la voce normale che si usa coi bambini: prima la faccia, non tutta la testa; se ti entra l'acqua nel naso si soffia, non si piange; le gambe dietro, non sotto; dieci minuti al giorno e poi non ti fa più paura niente. È la frase di Marisa, detta a due francesi nel 1997. Non risponde nessuno — la regola di Ada regge — e nessuna risposta è precisamente il risultato che si voleva.`,
  },

  ciro: {
    vittoria: `Ciro non ha detto niente a nessuno, che è quello che ha fatto per sessant'anni, ma ha cambiato una cosa: quando esce all'alba e vede due turisti che si mettono in acqua verso una caletta bella e sola, si avvicina col motore al minimo e dice due parole. «Là no. Là c'è la corrente.» Non è vero e lo sa. Tiene in barca la gaffa nello stesso posto e il rum nello stesso posto, e nella tasca della cerata c'è un foglietto piegato in quattro con un nome sopra, <b>Nicola Sperduto</b>, che si è fatto scrivere perché lui la grafia ce l'ha brutta. Nel cassetto, dove per sessant'anni c'è stata una cassetta, adesso non c'è niente. È la cosa che gli fa più piacere di tutta la faccenda.`,
    muta: `Ciro li ha portati fuori, li ha riportati dentro, e non ha aggiunto una parola: non per cattiveria, per sessant'anni di pratica nel non alzare la testa. Al terzo pontile, il giorno che sono partiti, ha sistemato una rete e non ha guardato il molo. Poi è tornato a casa, ha aperto il cassetto, ha guardato la cassetta e l'ha lasciata dov'era. Da quell'estate esce mezz'ora più tardi e rientra mezz'ora più presto, e a chi gli chiede perché dice che sono gli anni. Non sono gli anni. È che due persone gentili gli hanno chiesto una cosa e lui ha risposto a metà, e a settantadue anni certi conti si cominciano a fare.`,
    scambio: `Quella mattina la barca è rientrata in porto col motore al minimo, perché nessuno aveva il coraggio di mettere la marcia, e la marcia l'ha messa Ciro: qualcuno deve. Ha aspettato sul molo con Ada e non ha detto niente, e i quaranta euro che gli hanno messo in mano non li ha discussi, perché a discutere si fa peggio. Da quell'agosto tiene un quaderno a righe con le date in cui sente la corda, l'ora e il vento — l'ha imparato da un ingegnere — e una volta l'anno lo spedisce dentro una busta senza scriverci niente sopra, perché sa che dall'altra parte c'è qualcuno che quei numeri li sa leggere. Muore a ottantasei anni, in gennaio, nel suo letto. Il quaderno arriva anche quell'anno: l'aveva già imbustato.`,
    resta: `Ciro ha fatto la cosa più ventotenese possibile: non ha commentato. Ha annuito una volta, e la settimana dopo è passato dalle Parracine con due chili di totani e la scusa che non sapeva a chi darli. Poi ha appoggiato una gaffa nuova dietro la porta della stanza: «Sta lì. Non serve. Ma sta lì.» Tiene nella tasca della cerata un foglietto piegato in quattro con un numero di terraferma e una regola scritta da un altro — <i>se sente la corda, chiami; non risponda: chiami me</i> — e ha chiamato quattro volte in nove anni, sempre di notte, sempre con qualcuno che rispondeva al primo squillo. La sera, al terzo pontile, racconta il 2 settembre del '65 fino in fondo, compresa la parte che si era tenuto per sessant'anni.`,
  },

};

/* ---------- IMPRESE — achievement di fine partita ----------
   { flag, icon, title, desc } — sbloccata se G.flags[flag] è veritiero.
   Premiano le cose FATTE: i gesti affettivi come le scoperte. Le tre in fondo
   sono amare di proposito: anche le strade sbagliate sono state percorse. */

const IMPRESE = [

  /* --- giovedì 27 agosto: la vacanza --- */
  { flag: 'i_banda_foto',        icon: '📸', title: 'Cinque Foto Mosse nello Stesso Punto', desc: 'Una banda di sfocatura larga tre dita, sempre sopra lo stesso braccio di mare. Le ha salvate tutte e cinque: sarà la differenza tra credersi pazzi e sapere di non esserlo.' },
  { flag: 'avviso_fagiolini',    icon: '🫘', title: 'Dove C\'è la Gente',                   desc: 'Una signora di ottant\'anni, uno sgabello e un catino di fagiolini vi hanno dato l\'unica regola che conta su quest\'isola. E voi l\'avete ascoltata fino in fondo.' },
  { flag: 'i_foto_museo',        icon: '🖼', title: 'La Mano Tagliata dall\'Inquadratura',  desc: 'Molo di Napoli, 24 ottobre 1943. Una bambina col cappottino buono, e la mano di qualcuno che la foto taglia via all\'altezza del polso.' },
  { flag: 'visto_polpo',         icon: '🐙', title: 'Casa Sua',                             desc: 'Quattordici chili di polpo dentro una peschiera romana. Non c\'entrava niente con niente. Onestamente, avevate torto voi.' },
  { flag: 'boa_raggiunta',       icon: '🟡', title: 'La Boa',                                desc: 'Sessanta metri con il fondo che sotto è solo verde e poi solo blu. L\'ha toccata con tutte e due le mani. Questo non si cancella più.' },
  { flag: 'gaetano_crede',       icon: '🤝', title: 'Era una Nota',                          desc: '«Non ti dico che ti sei sbagliata: non ti sei mai sbagliata su una cosa che hai sentito.» Undici anni tardi. E in tempo.' },
  { flag: 'giorno_27_chiuso',    icon: '🌙', title: 'Il Primo Giorno',                       desc: 'Ventilatore a pale, lenzuolo fresco, la finestra aperta e l\'odore del limone in vaso. È l\'ultimo giorno che finisce bene, e lo avete vissuto per intero.' },

  /* --- venerdì 28 agosto: le cisterne --- */
  { flag: 'crafting_scoperto',   icon: '🔧', title: 'Il Tavolo Diventa un Banco',           desc: 'Lo zaino rovesciato su un tavolino di ferro alle otto e mezza del mattino. Da qui in poi, in questo gioco, le cose si mettono insieme.' },
  { flag: 'r_idrofono',          icon: '🎙', title: 'Si Fa Davvero Così',                   desc: 'Un microfono a clip dentro un preservativo, l\'aria spremuta fuori, il nodo sigillato col nastro. È come li fanno i biologi marini con quattro soldi. Funziona.' },
  { flag: 'mano_tenuta',         icon: '🤍', title: 'Quattro Secondi in una Cucina',        desc: 'Non gliel\'ha stretta: gliel\'ha tenuta. Ada guardava il catino delle patate come se fosse interessantissimo. Il gioco torna a questi quattro secondi quando serve.' },
  { flag: 'i_frase_scritta',     icon: '📓', title: 'Parola per Parola',                    desc: 'Scritta sul retro della ricevuta del traghetto con la penna del comodino, e cerchiata l\'ultima riga: quella che dice che qualcuno sa una cosa non pubblica.' },
  { flag: 'i_iscrizione',        icon: '🪨', title: 'SEX · QVINQVE CLAVSAE',                desc: 'Duemila anni fa, di sei stanze, cinque erano già chiuse. E sotto c\'era un ordine inciso a scalpello: NE APERIAT. Non si apra.' },
  { flag: 'muro_aperto',         icon: '🧱', title: 'Venti Centimetri di Malta del 1957',   desc: 'Il punto debole di un muro fatto in tre ore sta in alto, dove la malta è stata schiacciata di fretta contro una curva. Gaetano l\'ha trovato con le nocche.' },
  { flag: 'promessa_incisa',     icon: '⛏', title: 'Quattro Parole nel Tufo',              desc: 'Incise col coltellino a settanta centimetri da terra, all\'altezza di chi sta in ginocchio. E scritte al futuro, che è la parte coraggiosa.' },
  { flag: 'prima_apnea',         icon: '🫁', title: 'Quaranta Secondi, Quattordici Metri',  desc: 'È scesa lei, con la paura addosso e con lui che contava ad alta voce come promesso. Il Coro, in duemila anni, non aveva mai avuto una voce così.' },
  { flag: 'r_collana',           icon: '📿', title: 'Portare il Suo Nome',                  desc: 'Bronzo ossidato, tre lettere: IVL. Al collo si è scaldata subito. Meglio essere riconosciuti come chi porta un nome che come chi l\'ha rubato.' },
  { flag: 'risata_piazza',       icon: '😄', title: 'Undici Anni in una Frase',             desc: '«E scusa se ci ho messo undici anni a crederci.» Detta in piazza Castello, tra due vecchi che giocano a carte con un mazzo tenuto insieme da un elastico.' },
  { flag: 'bagno_ripreso',       icon: '🏖', title: 'Di Nuovo in Acqua',                    desc: 'Dopo la cisterna, dopo tutto: Cala Rossano alle sei e quaranta di sera, la ghiaia che fa male ai piedi, e rientrare in mare comunque.' },
  { flag: 'patto_trenta_secondi', icon: '⏱', title: 'Trenta Secondi, Sempre',              desc: 'Non «ti proteggo», non «te lo dico domani». Trenta secondi. È il patto più difficile del gioco, ed è quello che tiene in piedi tutto il resto.' },
  { flag: 'verita_detta',        icon: '🎧', title: 'Mezzo Secondo a Venticinque per Cento', desc: 'Gliel\'ha fatto sentire: volume a due tacche, un auricolare a testa, in mezzo a un ristorante. La verità detta regge — e più tardi lo dimostra in faccia a una cosa.' },
  { flag: 'file_cancellato',     icon: '🗑', title: 'Elimina Definitivamente? Sì',          desc: 'Aveva registrato sua moglie che dormiva. Ha cancellato la prova della cosa più importante che gli sia mai capitata, per una ragione più importante ancora.' },
  { flag: 'giorno_28_chiuso',    icon: '🌙', title: 'Il Secondo Giorno',                    desc: 'Le cisterne, la pietra, il ninfeo, la prima apnea. Siete tornati alle Parracine con le mani sbucciate e un pezzo di storia in tasca.' },

  /* --- sabato 29 agosto: Santo Stefano --- */
  { flag: 'ciro_in_squadra',     icon: '⚓', title: 'Chi Conosce il Mare',                  desc: 'Sale in barca con una busta della spesa e nomina ogni cosa che carica, come si nomina l\'attrezzatura prima di uscire. Da qui, nessuno annega per un solo errore.' },
  { flag: 'panopticon_visto',    icon: '👁', title: 'Novantanove Celle, un Punto Solo',     desc: 'Duecento metri di mulattiera tra i fichi d\'India col sole delle dieci, e poi il ferro di cavallo. Una macchina per guardare dentro tutto senza essere visti.' },
  { flag: 'cella_47_aperta',     icon: '🚪', title: 'L\'Unica Chiusa di Novantanove',       desc: 'Tutte le altre porte sono aperte o strappate dai cardini. La 47 no. E non era nemmeno bloccata: si apriva spingendo.' },
  { flag: 'i_graffito',          icon: '〰', title: 'Ottomilaquarantuno Tacche',            desc: 'Incise su un muro di calce, in righe da contare. Il carcere ha chiuso nel 1965. L\'ultima tacca è fresca.' },
  { flag: 'contato_in_tre',      icon: '🔢', title: 'Non Mi Fido del Campione',             desc: 'La stima non tornava e Gaetano non si è fidato: le ha contate tutte, a mano, in tre. Questo gioco vuole bene alle persone precise, e qui lo dimostra.' },
  { flag: 'i_osso',              icon: '🕯', title: 'Una Fossa in Più',                     desc: 'Croci di ferro tondo saldate a mano, con i numeri dipinti in bianco e nessun nome. E una fossa in più di quelle che i numeri contavano.' },
  { flag: 'nastro_risparmiato',  icon: '🤚', title: 'Il Pollice si Alza',                   desc: 'Il tasto era già premuto e l\'avete lasciato andare, piano, come si stacca la mano da una cosa calda. Vi siete disarmati per non svegliare niente.' },
  { flag: 'nastro_suonato',      icon: '📻', title: 'PLAY',                                 desc: 'Il clac della plastica del 1965, che è un clac che la plastica non sa più fare. Ciro vi aveva avvertiti due volte. Adesso avete l\'arma migliore che c\'è, e l\'avete pagata.' },
  { flag: 'ciro_ha_urlato',      icon: '🪝', title: 'Per la Cintura',                       desc: 'Vi ha tirati fuori uno per uno con una forza che a settantadue anni non dovrebbe avere, e che invece hanno tutti quelli che per cinquant\'anni hanno tirato a bordo pesci grossi.' },
  { flag: 'giorno_29_chiuso',    icon: '🌙', title: 'Il Terzo Giorno',                      desc: 'Ada ha lasciato accesa la lampadina sotto la pergola e un piatto coperto da un altro piatto. Dopo Santo Stefano, una cosa così vale più di un\'arma.' },

  /* --- domenica 30 agosto: il giorno che non finisce --- */
  { flag: 'd_ora_misurata',      icon: '⏱', title: 'La Campana Contro l\'Orologio',        desc: 'Cronometrata fino in fondo, senza distogliere lo sguardo. Ogni volta che una cosa impossibile riceve un numero, il Coro perde una nota.' },
  { flag: 'd_prova_regge',       icon: '📷', title: 'La Foto di STAMATTINA',                desc: 'Stessa bottiglia, stessa ombra, stessa ora. La prova che il giorno è lo stesso non stava nel cielo né nella gente: stava nel telefono.' },
  { flag: 'specchio_smascherato', icon: '💍', title: 'Dove Sono le Tue?',                   desc: 'Due fedi su un filo di nylon, mostrate a una cosa che aveva la sua faccia e la sua cadenza. Non ha saputo rispondere.' },
  { flag: 'pronti_per_la_fossa', icon: '🎒', title: 'Lo Zaino dell\'Ultima Volta',          desc: 'Torcia, coltello, tutto, preparato con la calma di chi sa che stavolta non si torna indietro a prendere niente.' },
  { flag: 'assuntina_dorme',     icon: '🎵', title: 'La Seconda Strofa',                    desc: 'Ottantadue anni ad aspettare che qualcuno la cantasse. Claudia canta male. A nessuno è mai importato meno di adesso.' },

  /* --- misteri risolti --- */
  { flag: 'sa_sesta_cisterna',   icon: '🗝', title: 'La Sesta Non è Perduta',               desc: 'Sta sotto le altre cinque, sotto il livello del mare, e non è una cisterna: è la bocca. I romani non le hanno scavate per l\'acqua. E una bocca si può richiudere.' },
  { flag: 'sa_nome_guardia',     icon: '🗝', title: 'Nicola Sperduto, Quarantatré Anni',    desc: 'Nella cella 47 non c\'era un detenuto: c\'era la guardia, rimasta a fare il turno in un carcere vuoto fino a morirci. Da stanotte c\'è qualcuno che lo sa.' },
  { flag: 'sa_ninnananna',       icon: '🗝', title: 'Si Chiamava Assuntina',                desc: 'Sei anni, aggiunta a penna in fondo a una lista battuta a macchina. Non chiamava nessuno: aveva paura, e sua madre le aveva detto che se canti forte la paura non ti sente.' },

  /* --- le cose messe insieme che contano --- */
  { flag: 'r_torcia',            icon: '🔦', title: 'Mani Libere',                          desc: 'Tre giri di nastro attorno al cinturino della maschera. Sembra una scemenza: laggiù, con una mano occupata, non ti tiri su.' },
  { flag: 'r_salamoia',          icon: '🧂', title: 'La Loro Stessa Acqua',                 desc: 'Sale di questo mare disciolto nell\'acqua di quella cisterna. Gli fa male non perché gli ricorda cosa sono: perché gli ricorda cosa non sono più.' },
  { flag: 'r_bombola',           icon: '🤿', title: 'Quattro Minuti Sono Due Minuti',       desc: 'Rubinetto nuovo, guarnizione ricavata da una camera d\'aria, duecento bar in tre litri. Ottanta di aria e cinque metri in più, ogni volta che scendete.' },
  { flag: 'r_ninnananna',        icon: '🎼', title: 'L\'Unica Cosa Gentile',                desc: 'Una foto del 1943 e una medaglietta di bronzo, tenute vicine finché una cosa non ha avuto senso. Non è un\'arma, e non ne avevate altre di gentili.' },
  { flag: 'r_ancora_completa',   icon: '⚓', title: 'L\'Àncora di Voce',                    desc: 'Una guardia che piange nel 1965 e una donna che canta nel 2026, sulla stessa bobina. Duemila anni, e nessuno era mai sceso con un\'àncora.' },
  { flag: 'r_fedi',              icon: '💍', title: 'Le Due Fedi',                          desc: 'Non fa danni, non cura, non illumina, non taglia. Due anelli di oro giallo su un filo da pesca da venti chili. È un indirizzo.' },

  /* --- come è finita --- */
  { flag: 'usciti_vivi',         icon: '⛵', title: 'Il Traghetto delle 17:30',             desc: 'Ha mollato gli ormeggi in orario. L\'isola si stacca — è lei che si stacca, non tu che vai via — e voi eravate sopra.' },
  { flag: 'coro_zitto',          icon: '🤫', title: 'Solo il Rumore dell\'Acqua',           desc: 'Fuori dall\'acqua alle 06:12, dalla scaletta di ferro di Cala Rossano. Il mare non fa niente. Non calmo nel senso bello: FERMO.' },
  { flag: 'marisa_restituita',    icon: '☕', title: 'Il Nome di Sua Sorella',               desc: 'Marisa. Detto da qualcuno che l\'ha sentita davvero. È la sola cosa che si potesse dare ad Ada, e gliel\'avete data prima di partire.' },
  { flag: 'cavallino_restituito', icon: '🐴', title: 'Una Zampa Manca',                     desc: 'Giallo, era. Ottantadue anni sotto sale e ancora la faccia allegra. Non l\'avete tenuto: l\'avete riportato dove andava.' },
  { flag: 'fedi_in_mare',        icon: '💧', title: 'A Metà Canale, Sopra la Fossa',        desc: 'Slegate dal filo e lasciate andare, alle 19:47, mentre il mare andava di rame. Non era un gesto: era un indirizzo consegnato a mano.' },
  { flag: 'scambio_fatto',       icon: '🕳', title: 'Una Persona in Meno',                  desc: 'Uno ha spinto l\'altro verso l\'alto, e a spingere verso l\'alto si va giù. Non c\'è stata una battaglia: c\'è stata una decisione, in due secondi, a quaranta metri.' },
  { flag: 'uno_resta',           icon: '🏝', title: 'Dieci Minuti al Giorno',               desc: 'Nessuno l\'ha obbligato, nessuno l\'ha preso, nessuno è morto. La parte terribile non è che sia sbagliato: è che sia generoso.' },
  { flag: 'restati_in_due',      icon: '🏠', title: 'Stare',                                desc: 'Duemila anni di gente portata qui contro la propria volontà. E adesso ci sono due che ci restano perché hanno deciso, e che potrebbero partire domani.' },
  /* 🌊 È RIMASTO: uno stato che NON è la morte. Il motore lo tiene separato, e queste
     tre imprese lo dicono per nome — una per persona, perché non è la stessa cosa. */
  { flag: 'rimasto_claudia',     icon: '🌊', title: 'Claudia è Rimasta',                    desc: 'Non l\'hanno presa: ha scelto. Una donna che ha avuto paura dell\'acqua profonda per tutta la vita è rimasta su uno scoglio da ottocento abitanti per insegnare a nuotare a una bambina del 1943. Respira. È a Cala Rossano, ogni mattina alle sette.' },
  { flag: 'rimasto_gaetano',     icon: '🌊', title: 'Gaetano è Rimasto',                    desc: 'Non l\'hanno preso: ha scelto. Un uomo che misura cose a settecento chilometri è rimasto a misurare dodici ore di niente al giorno, in una cantina, per mettersi in mezzo fra quella cosa e i prossimi che arrivano. Come Nicola Sperduto, ma con la corrente elettrica.' },
  { flag: 'rimasto_ciro',        icon: '🌊', title: 'Ciro è Rimasto',                       desc: '«Appunto, signò. Qualcuno deve restare a casa.» Non l\'hanno preso e non se n\'è andato: ci era già. Adesso è la guardia di un\'isola che non sa di averne una.' },
  { flag: 'tornati_dal_checkpoint', icon: '🛏', title: 'Vi Svegliate Asciutti',             desc: 'Siete caduti tutti, e il Coro non vi ha uccisi: vi ha RIMESSI A POSTO, come si rimette a posto un giocattolo che serve ancora. Avete ricominciato la giornata sapendo cosa vi mancava, per nome. Ed è la parte peggiore.' },
  { flag: 'seconda_strofa_cantata', icon: '🎼', title: 'Mentre Affondavate',                desc: 'A una bambina di sei anni, con il fiato che finiva, e senza sbagliare una parola. Non ha salvato voi. L\'ha fatta dormire.' },
  { flag: 'loop_infinito',       icon: '♾', title: 'Nove',                                 desc: 'Il fico è nello stesso punto del piatto e la mosca gli gira intorno nello stesso senso. Nove volte. E sul foglietto attaccato allo specchio qualcuno sta imparando a scrivere.' },

  /* --- le strade sbagliate. Le avete percorse: contano uguale. --- */
  { flag: 'bugia_detta',         icon: '🍽', title: 'Un Motore Lontano',                    desc: 'Una bugia gentile detta a cena, per proteggerla. Lei ha risposto «ah, ok», ha ripreso la forchetta ed è tornata a mangiare, ed è mille volte peggio di un litigio.' },
  { flag: 'risposto_appello',    icon: '🗣', title: 'Presente',                             desc: 'In ginocchio davanti a un canale romano, con la bocca a dieci centimetri dall\'acqua. Il brusio non si è abbassato: si è FERMATO, tutto insieme. Adesso siete nella lista.' },
  { flag: 'ascoltato_troppo',    icon: '🎧', title: 'Altri Trenta Secondi',                 desc: 'La testa fuori bordo, l\'orecchio dentro quel ronzio, trenta secondi in più perché volevate sapere. Ascoltare è naturale. Si paga davanti a tutti.' },
  { flag: 'hanno_risposto',      icon: '🎵', title: 'Una Sillaba',                          desc: 'Ada l\'aveva detto in cucina con un bicchiere d\'acqua in mano che non beveva: non si risponde. Una sillaba è tutto quello che serviva.' },
  { flag: 'non_hanno_capito',    icon: '🌫', title: 'Salvi, a Mani Vuote',                  desc: 'Vivi tutti e due, in piedi, nessuno vi ha presi. E un buco con i bordi. «Era qualcosa?» «Sì.» «Cosa?» «Non lo so.»' },
];

/* ---------- CRONACHE DI FUORI ----------
   Righe di mondo mostrate nel finale solo se il flag è attivo. Servono `icon` e
   `text`: engine.js le stampa come `${c.icon} ${c.text}`. Non raccontano di nuovo
   il finale: raccontano cosa è rimasto acceso, altrove, per colpa vostra. */

const CRONACA = [

  /* ---- LE RIGHE DEI FINALI E DELLE DECISIONI IRREVERSIBILI ----
     Ventotto flag stavano nelle scene d'epilogo e nelle scelte che non si
     ritirano — cioe' nei punti in cui il gioco chiede di piu' — e non venivano
     riletti da nessuna parte, perche' il gioco finisce li'. Una decisione
     irreversibile che non lascia un segno nel mondo non e' irreversibile: e'
     solo l'ultima schermata. */
  { flag: 'hanno_scelto_di_andarsene', icon: '⛴', text: 'Sotto Ventotene e\' rimasto tutto quello che c\'era, e nessuno lo ha toccato. Due persone hanno preso il traghetto delle diciassette e trenta e non sono mai piu\' tornate sull\'isola — nemmeno per una domenica, nemmeno per far vedere il posto a qualcuno. Il gioco non li giudica, e nemmeno noi.' },
  { flag: 'tre_volte_rimessi_a_posto', icon: '🔁', text: 'Tre volte lo stesso giorno, e tre volte le stesse valigie rifatte con la stessa piega delle maniche in dentro. Alla terza, uno dei due ha smesso di piegarle.' },
  { flag: 'traghetto_partito',     icon: '🚢', text: 'Il traghetto delle diciassette e trenta e\' partito con due passeggeri in piu\' di quanti ne aspettasse la biglietteria, e la biglietteria non se n\'e\' accorta. A Formia, sulla banchina, uno dei due si e\' voltato a guardare il mare aperto per un tempo che l\'altro non ha interrotto.' },
  { flag: 'tramonto_visto',        icon: '🌅', text: 'Due ore e quaranta di vento sul ponte di poppa, e il sole che se ne va a dritta dietro Ponza. Chi c\'era dice che e\' stato il tramonto piu\' bello della sua vita, e lo dice con una faccia che non e\' del tutto contenta.' },
  { flag: 'fedi_rimesse',          icon: '💍', text: 'Le due fedi sono tornate al loro posto sul filo di nylon, e il filo di nylon e\' finito in un cassetto insieme allo scontrino di marzo delle due maschere identiche. Il cassetto non si apre spesso.' },
  { flag: 'posto_vuoto',           icon: '🪑', text: 'Al tavolino della Terrazza di Mimi\', d\'estate, c\'e\' un posto che il cameriere apparecchia sempre e che nessuno occupa. Nessuno gliel\'ha chiesto. Lo fa da quell\'anno.' },
  { flag: 'promessa_riferita',     icon: '🤍', text: 'Una promessa fatta a quarantacinque metri e\' stata riferita a chi doveva sentirla, in superficie, con parole diverse ma con lo stesso peso. Chi l\'ha riferita non ha aggiunto niente di suo, ed e\' la cosa piu\' difficile che abbia fatto.' },
  { flag: 'sentita_la_voce',       icon: '🎧', text: 'C\'e\' una registrazione di undici secondi che due persone hanno riascoltato insieme, una volta sola, e poi mai piu\'. Non e\' stata cancellata: sta in una cartella con un nome che non dice niente, e tutte e due sanno dov\'e\'.' },
  { flag: 'benedetta_la_scelta',   icon: '🕯', text: 'Chi e\' rimasto e\' stato benedetto da chi e\' salito, con una frase detta ad alta voce sulla rampa, davanti a un marinaio che non ha capito e non ha chiesto.' },
  { flag: 'chi_ha_scelto_di_restare', icon: '🏠', text: 'Non e\' un sacrificio: e\' una scelta, fatta da sveglio, alla luce, con l\'altro che guardava. Al Comune di Ventotene risulta una denuncia di scomparsa mai chiusa, e in due paesi diversi ci sono persone che sanno che non e\' vero.' },
  { flag: 'chi_e_rimasto',         icon: '🌊', text: 'Chi e\' rimasto e\' diventato una voce, e a chi ascolta col giusto strumento, nel punto giusto, ogni tanto capita di sentirla — e di riconoscerla, che e\' la parte che nessuno racconta.' },
  { flag: 'negata_la_voce',        icon: '🔇', text: 'Le due voci nuove nel Coro sono le ultime che si sono aggiunte. Le altre le hanno accolte come si accoglie qualcuno che era atteso, e questa e\' la cosa peggiore di tutta questa storia.' },
  { flag: 'presi_dal_coro',        icon: '🎵', text: 'Non e\' una morte: e\' una collezione. E una collezione, per definizione, non e\' finita.' },
  { flag: 'cerca_differenza',      icon: '🔁', text: 'C\'e\' chi ha smesso di contare i cicli e ha cominciato a cercare la differenza: qualcosa che il trenta agosto non rifa\' uguale. La cerca ancora, e l\'ha quasi trovata due volte.' },
  { flag: 'non_alzati',            icon: '🛏', text: 'Alcune mattine non ci si alza, e il giorno ricomincia lo stesso alle sette e dieci. Questa e\' l\'unica cosa che il trenta agosto non punisce.' },
  { flag: 'd14_parlato',           icon: '🗣', text: 'Al Coro e\' stato risposto a voce, sott\'acqua, con l\'erogatore in bocca. Nessuno ha capito cosa sia stato detto, nemmeno chi lo ha detto.' },
  { flag: 'd_capito_tutto',        icon: '🧩', text: 'Qualcuno, a dieci metri di profondita\' e con l\'aria contata, ha messo insieme tutti i pezzi nello stesso momento. Non gli e\' servito a niente, e li ha messi insieme lo stesso.' },
  { flag: 'd_banchina_finale',     icon: '⚓', text: 'Sulla banchina di Porto Romano, davanti al portellone aperto, si prende una decisione che non si puo\' ritirare. Non c\'e\' un dado. Il gioco lo dice una volta sola e poi sta zitto.' },
  { flag: 'giulia_risparmia',      icon: '📿', text: 'A una donna morta di fame nel 14 dopo Cristo e\' stata data una data invece di una speranza, ed e\' bastato. Da allora, nel ninfeo di Villa Giulia, l\'idrofono non registra piu\' niente.' },
  { flag: 'marisa_documentata',    icon: '📷', text: 'Da qualche parte esistono le fotografie di una donna a quarantacinque metri, muta e faccia, riprese per intero. Non sono mai state pubblicate. Chi le ha fatte le tiene per un motivo che non ha mai spiegato del tutto.' },
  { flag: 'maschera_restituita',   icon: '🤿', text: 'Sul sedimento della fossa, a due metri da lei, e\' appoggiata una maschera da sub degli anni Novanta, rimessa dritta con il vetro verso l\'alto. E\' l\'unica cosa in questa storia che qualcuno abbia restituito.' },
  { flag: 'file_stiva_cancellato', icon: '🗑', text: 'Il file della stiva e\' stato cancellato dalla scheda, dal cestino e dal backup, e la scheda e\' stata formattata due volte. Chi l\'ha fatto e\' una fotografa, e non cancella mai niente.' },
  { flag: 'nome_valigia',          icon: '🧳', text: 'Su una valigia di cartone pressato, a quarantacinque metri, c\'e\' un nome scritto a inchiostro che il sale non ha portato via. Adesso quel nome sta anche su un foglio, in una casa, in un cassetto.' },
  { flag: 'prezzo_dei_cinque_secondi', icon: '⏱', text: 'Cinque secondi in piu\', a quarantacinque metri, hanno un prezzo che non e\' scritto su nessuna tabella decompressiva. Il conto lo tiene qualcun altro, ed e\' preciso.' },
  { flag: 'reclamati',             icon: '📋', text: 'Su un verbale del 1943 c\'e\' scritto NON RECLAMATI accanto a un elenco di nomi. Ottantatre\' anni dopo, qualcuno li ha reclamati — ad alta voce, sulla rampa di un traghetto, con la pagina strappata in mano.' },
  { flag: 'signora_muta',          icon: '🫘', text: 'A una signora seduta a un tavolino, in un paese vuoto, e\' stata data la risposta sbagliata. Lei non ha corretto nessuno: ha continuato a pulire i fagiolini, e quello che sapeva se l\'e\' tenuto un altro giro.' },
  { flag: 'cena_paese',            icon: '🍝', text: 'C\'e\' una sera, alla Terrazza di Mimi\', di cui in questa famiglia si parla ancora: il vino della casa, la frittura, e due persone che ridevano cosi\' forte che si sono girati i tavoli accanto. E\' l\'ultima sera in cui non sapevano niente.' },
  { flag: 'vista_peschiera',       icon: '🐟', text: 'A Punta Eolo, dentro il bacino grande della peschiera romana, l\'acqua e\' alta un palmo ed e\' calda come una pozza. Ci sono due impronte di piedi nudi nel sedimento, di due misure diverse, e nessun cartello dice che non si puo\'.' },

  /* ---- LE VENTIQUATTRO RIGHE DELLE PROVE FALLITE (e di due riuscite) ----
     Le ventisette prove aggiunte per la soglia dell'incertezza si portavano
     dietro ventotto scene e altrettanti flag NUOVI — e un flag senza consumatore
     e' una promessa non mantenuta: il gioco registra che il giocatore ha vissuto
     una cosa e poi non gliela dice mai piu'. Qui ognuno ha la sua riga di mondo,
     che e' il posto giusto: nessuna di queste cose cambia il finale, ma tutte
     lasciano un segno da qualche parte, ed e' quello che le rende successe. */
  { flag: 'b_stanza_ripresa',  icon: '📷', text: 'Su un hard disk esterno, in una cartella chiamata <i>VENTOTENE_grezzi</i>, c\'e\' un file di quaranta secondi che nessuno ha piu\' aperto. Nell\'inquadratura, al secondo diciannove, in fondo a destra, c\'e\' una cosa che nella stanza non era stata vista. Claudia lo sa. Non lo ha mai riaperto, e non ha nemmeno mai cancellato la cartella.' },
  { flag: 'b_vista_la_mano',   icon: '🕳', text: 'C\'e\' una regola nuova, in questa coppia, e non e\' mai stata detta ad alta voce: quando si scende da qualche parte, la torcia la tiene chi sale per ultimo. Chi chiedesse perche\' si sentirebbe rispondere che e\' piu\' pratico.' },
  { flag: 'gaffa_storta',      icon: '⚓', text: 'La gaffa di Ciro e\' stata raddrizzata col martello su un cuneo di legno, di notte, dietro il B&B, da un uomo che non aveva mai raddrizzato niente in vita sua. Ciro se n\'e\' accorto il giorno dopo e non ha detto niente — che, con Ciro, e\' il complimento piu\' grosso che esista.' },
  { flag: 'promessa_mai_soli', icon: '🖤', text: 'Fra le regole di casa, adesso, ce n\'e\' una che vale sopra tutte le altre e che non ammette eccezioni nemmeno per scherzo: <i>mai piu\' tu da solo sul filo di una cosa.</i> E\' stata detta a novanta metri sul mare, in ginocchio, e da allora e\' stata invocata due volte — una per una scala a pioli e una per una decisione di lavoro.' },
  { flag: 'collana_a_claudia', icon: '📿', text: 'La medaglietta di bronzo con le tre lettere sta al collo di Claudia, sotto la maglietta, appesa a un filo di nylon da tre decimi annodato da lei. Il nodo tiene. Lo ha rifatto una volta sola, in undici anni, quando il nylon si e\' ingiallito.' },
  { flag: 'ha_contato_con_lui',icon: '🪜', text: 'Da qualche parte, in una casa a Roma, c\'e\' un uomo di quarantadue anni che quando fa una salita lunga conta a voce bassa. Non conta i gradini: conta i respiri, e li conta con la cadenza con cui glieli contava lei, appesa a otto metri dal bordo di un pozzo romano.' },
  { flag: 'simone_amico',      icon: '🤿', text: 'A Cala Rossano, il ragazzo del noleggio ha aggiunto una riga sul foglio a quadretti del padre: <i>due giorni — prezzo isola.</i> Il padre gliel\'ha cancellata. Lui l\'ha riscritta.' },
  { flag: 'simone_conosce',    icon: '🎓', text: 'Un ragazzo di ventidue anni ha passato l\'esame di oceanografia fisica raccontando alla commissione l\'anomalia batimetrica di Cala Rossano, con dei numeri che nessun libro di testo riportava. Alla domanda su dove li avesse presi ha risposto: <i>"me li ha spiegati uno in barca"</i>. Ha preso trenta.' },
  { flag: 'teneva_dal_quarto', icon: '🤝', text: 'Sulla rampa senza ringhiera del secondo ordine di Santo Stefano, il quattordicesimo gradino non c\'e\' piu\' da sessant\'anni. Adesso c\'e\' un pezzo di nastro adesivo bianco sulla parete, all\'altezza della mano, messo da qualcuno che non lavora per il Parco. Nessuno lo ha tolto.' },
  { flag: 'non_si_porta_a_pezzi', icon: '🧱', text: 'In una casa dove si conservano i biglietti dei traghetti dal 2015, non c\'e\' nessun pezzo di muro di Santo Stefano. E\' l\'unica cosa che sarebbe stato facile portare via, ed e\' l\'unica che non e\' stata portata via.' },
  { flag: 'mano_rallentava',   icon: '✏️', text: 'Su un quaderno a righe, sotto la data del 29 agosto, c\'e\' un conto che non torna e una frase sotto: <i>"non e\' che il conto non torna. E\' che la mano rallentava."</i> La frase e\' sottolineata due volte, e la seconda sottolineatura e\' stata fatta molto dopo.' },
  { flag: 'data_trovata_da_lei', icon: '📕', text: 'In un archivio senza corrente, sopra due registri aperti alla stessa pagina, e\' stata risolta una data che un ingegnere aveva sbagliato per mezz\'ora. L\'ha risolta una fotografa, notando che il maresciallo che teneva il PRESENZE era nato nel 1903. Da allora, in quella coppia, "leggilo tu" e\' una frase che si dice senza vergogna.' },
  { flag: 'ciro_fara_vedere',  icon: '🚤', text: 'Ciro non ha detto la terza cosa. Ha fatto meglio: alla fine dell\'estate ha portato la barca in un punto preciso fra Ventotene e Santo Stefano, ha spento il motore, e ha aspettato senza dire niente finche\' non si e\' sentita. Poi ha riacceso e non ne ha piu\' parlato.' },
  { flag: 'dentro_quattro_fuori_sei', icon: '🫁', text: 'C\'e\' un modo di respirare che si insegna ai sub e che questa coppia usa in coda alla posta, prima dei colloqui e la sera in cui e\' arrivata quella telefonata: <i>dentro quattro, fuori sei.</i> L\'hanno imparato sulla soglia di una cisterna romana, ed e\' l\'unica cosa utile che quel posto abbia mai regalato a qualcuno.' },
  { flag: 'i_numeri_dopo',     icon: '📐', text: 'In un ufficio dove si progettano satelliti c\'e\' un uomo che, prima di dare i numeri a qualcuno, si ferma mezzo secondo e si chiede se e\' il momento. Non gli riesce sempre. Gli riesce molto piu\' spesso di prima, e la differenza l\'ha imparata su un terrazzamento di Santo Stefano.' },
  { flag: 'tasto_rotto',       icon: '⏹', text: 'Il Geloso del 1965 e\' stato portato da un tecnico a Formia, che ha detto che il tasto STOP va sostituito e che il pezzo non esiste piu\'. Sta su una mensola, con la spina staccata, e la spina staccata e\' l\'unica cosa che lo tiene fermo.' },
  { flag: 'regola_di_ciro',    icon: '🧭', text: 'Su un gozzo di Porto Romano vale una regola che il padrone ha detto una volta sola: <i>"in barca, quando non sapete, chiedete. Non e\' vergogna: e\' che qua l\'errore lo paga sempre un altro."</i> Chi l\'ha sentita la ripete al lavoro, senza citare la fonte, e nessuno gli ha mai chiesto da dove venisse.' },
  { flag: 'lezione_di_ada',    icon: '🌊', text: 'In un quaderno di appunti tecnici, in mezzo a delle misure in centimetri, c\'e\' una frase scritta a stampatello: <b>I CENTIMETRI LI TENETE VOI.</b> Chi l\'ha scritta la usa quando un modello non spiega una cosa che la gente del posto sa da sempre.' },
  { flag: 'claudia_ha_rimesso_a_posto', icon: '🫂', text: 'Sopra una fossa di quarantacinque metri, a una bambina morta nel 1943 e\' stata detta una frase sbagliata e poi una giusta, a quattro minuti di distanza. La giusta l\'ha detta Claudia: <i>"di te no. Di te mai."</i> L\'increspatura si e\' allargata, e chi c\'era non lo ha piu\' raccontato a nessuno.' },
  { flag: 'ciro_sorella_raccontata', icon: '🥃', text: 'Quaranta minuti fermi al sole, in una barca sopra una fossa, sono bastati a un uomo di settantadue anni per raccontare di sua sorella. Non lo aveva mai fatto. Non lo ha piu\' rifatto. Ma adesso c\'e\' qualcuno al mondo che sa come si chiamava.' },
  { flag: 'cima_rientrata',    icon: '🪢', text: 'A quarantacinque metri, dentro la stiva di una nave del 1943, c\'e\' una cima che una volta e\' rientrata di trenta centimetri mentre nessuno la tirava. Chi l\'ha vista non lo ha scritto nel Quaderno. Lo ha detto a voce, una volta, in cucina, e poi non piu\'.' },
  { flag: 'stessa_bombola',    icon: '🤿', text: 'Per quindici metri di risalita, due persone hanno respirato dalla stessa bombola, faccia a faccia, con un braccio ciascuno intorno all\'altro. Nei corsi lo chiamano <i>assetto d\'emergenza in coppia</i>. Nessuno dei due lo ha mai chiamato cosi\'.' },
  { flag: 'conto_con_la_mano', icon: '✋', text: 'Alla sosta dei dieci metri, quando il conto e\' saltato tre volte perche\' qualcuno contava mezzo numero avanti, il conto l\'ha tenuto una mano: una stretta al secondo, centoquaranta volte. Da allora, quando uno dei due non riesce a dormire, l\'altro gli stringe la mano una volta al secondo e nessuno dei due dice perche\'.' },
  { flag: 'bocca_piu_grande',  icon: '🕳', text: 'Dal ponte di un traghetto che va a diciotto nodi, a due miglia dall\'isola, si vede un\'ombra fra due parracine larga come una porta. Chi l\'ha guardata per undici minuti giura che era piu\' grande di come l\'aveva lasciata. Chi era con lui gli ha detto di non guardarla, e da allora, quando partono, guardano tutti e due la prua.' },
  { flag: 'marisa_restituita',  icon: '☕', text: 'Alle Parracine, sul foglietto attaccato allo specchio con il nastro, c\'è una riga nuova nella grafia di Ada: <i>"la stanza con la terrazza non si affitta il 30 agosto"</i>. Il figlio le ha chiesto perché. Ada ha risposto che d\'agosto è tutto pieno comunque, che non è una risposta, e infatti lui non ha insistito.' },
  { flag: 'sa_nome_guardia',   icon: '🕯', text: 'All\'archivio di Stato di Napoli, un impiegato ha trovato una richiesta di consultazione arrivata per posta, scritta a mano, con un nome e una data: <b>Nicola Sperduto, 2 settembre 1965</b>. L\'ha cercato. C\'era. Non risultava trasferito, non risultava dimesso, non risultava morto. L\'impiegato ha fotocopiato la pagina e se l\'è portata a casa, e ancora non sa dire perché.' },
  { flag: 'sa_ninnananna',     icon: '🎼', text: 'Su un forum di canti popolari campani è comparsa la trascrizione di una ninnananna in due strofe che nessuno aveva mai messo per scritto. Tre etnomusicologi discutono da mesi sull\'autenticità della seconda: dicono che è troppo consolatoria per essere antica. Un utente senza foto profilo ha scritto una riga sola: <i>"è del 2026"</i>. Nessuno gli ha creduto.' },
  { flag: 'sa_sesta_cisterna', icon: '🧱', text: 'Il Comune ha messo una transenna e un cartello nuovo dietro l\'orto dei Coraggio: <i>PERICOLO — CAVITÀ.</i> Nessuno ha chiesto il sopralluogo, nessuno ha aperto una pratica: la transenna è comparsa e basta, e i vecchi del paese la guardano passando e non dicono niente, come se l\'avessero già vista una volta, da bambini.' },
  { flag: 'promessa_incisa',   icon: '⛏', text: 'Dentro una cisterna che nessuno riaprirà, a settanta centimetri da terra — l\'altezza di chi sta in ginocchio — ci sono quattro parole incise col coltellino. Nessun archeologo le vedrà mai, e questa è l\'unica cosa che a chi le ha incise andava bene fin dall\'inizio.' },
  { flag: 'mano_tenuta',       icon: '🤍', text: 'Ada ha smesso di sbucciare le patate asciutte. Le mette a bagno, come si fa. Alla figlia che gliel\'ha fatto notare ha risposto che a una certa età le mani si stancano — e non è vero, e la figlia lo sa, e in questa famiglia si è capito da tre generazioni che certe cose si lasciano stare.' },
  { flag: 'gaetano_crede',     icon: '📐', text: 'In un ufficio dove si progettano satelliti c\'è una regola nuova, non scritta, che nessuno sa da dove venga: quando un collega dice di aver visto o sentito una cosa che non torna, non si risponde «avrai sbagliato». Si chiede l\'ora esatta e si scrive. Funziona sorprendentemente bene anche sui guasti veri.' },
  { flag: 'ciro_in_squadra',   icon: '⚓', text: 'Al terzo pontile, la sera, un vecchio racconta il 2 settembre del 1965 a chi si siede: che gli uomini non parlavano, che una guardia piangeva, e che suo padre quella notte legò le barche e disse a tutti di non uscire fino all\'alba. Da qualche mese lo racconta fino in fondo, compresa la parte che si era tenuto per sessant\'anni.' },
  { flag: 'nastro_suonato',    icon: '📻', text: 'In una casa di Ventotene c\'è un cassetto che per sessant\'anni ha contenuto una cassetta senza custodia. Adesso è vuoto, e il proprietario lo apre una volta al mese per controllare che sia ancora vuoto. È l\'unica cosa di tutta la faccenda che gli dà una soddisfazione piena.' },
  { flag: 'nastro_risparmiato', icon: '🤚', text: 'C\'è un registratore Geloso, a batterie, con dentro una cassetta e il tasto PLAY ancora alzato, chiuso in una scatola da scarpe in fondo a un armadio a duecento chilometri dal mare. Funziona. Chi ce l\'ha messo controlla le batterie ogni sei mesi e non le toglie: se le togliesse, un giorno, qualcuno potrebbe pensare che non serviva.' },
  { flag: 'coro_zitto',        icon: '🌊', text: 'Al diving del porto, l\'estate dopo, Simone — che adesso ha ventitré anni e il terzo anno da dare — ha notato una cosa che non sa spiegare e ha smesso di raccontarla ai turisti: quel brusio che si sentiva sopra la franata, oltre la boa gialla, non c\'è più. Ha cambiato idrofono due volte pensando che fosse rotto.' },
  { flag: 'assuntina_dorme',   icon: '🌙', text: 'Nell\'archivio di una compagnia di navigazione, su una lista d\'imbarco del 24 ottobre 1943, l\'ultimo nome è aggiunto a penna in fondo, in fretta. Qualcuno, di recente, gli ha messo accanto una crocetta a matita e nient\'altro. La matita è morbida, il tratto è fresco, e non c\'è nessuna procedura d\'archivio che preveda una crocetta.' },
  { flag: 'cavallino_restituito', icon: '🐴', text: 'A quarantacinque metri, dentro la stiva di un piroscafo spezzato in due, un cavallino di celluloide giallo con una zampa in meno è tornato esattamente dove stava. Un sub tecnico l\'ha filmato l\'anno dopo e nel video si sente che dice, dentro l\'erogatore, una parola sola: <i>"strano"</i>.' },
  { flag: 'i_iscrizione',      icon: '📄', text: 'Alla Soprintendenza è arrivata, senza firma, una busta con la fotografia di un\'iscrizione romana: <b>CASTELLVM AQVAE · CVBICVLA SEX · QVINQVE CLAVSAE · NE APERIAT</b>. È stata catalogata, protocollata e archiviata in un mese. Il funzionario che l\'ha aperta ha letto la traduzione a voce alta due volte e poi ha chiuso la finestra dell\'ufficio, che era agosto.' },
  { flag: 'patto_trenta_secondi', icon: '⏱', text: 'In una casa della provincia di Latina c\'è una regola che non sta scritta da nessuna parte e che vale su tutto: se una cosa fa paura, si dice entro trenta secondi. Ha rovinato due cene, salvato un lavoro, e reso impossibile litigare per più di un giorno. Non hanno mai spiegato a nessuno da dove viene.' },
  { flag: 'bugia_sepolta',     icon: '🍽', text: 'Al ristorante con la terrazza, in agosto, c\'è un tavolo contro la ringhiera che due clienti chiedono ogni anno. Ogni anno la conversazione arriva a un certo punto, si ferma, e riparte da un\'altra parte. Il cameriere l\'ha notato al terzo anno. Non porta più il vino a quel momento: aspetta due minuti.' },
  { flag: 'foto_salvate',      icon: '💾', text: 'Su un hard disk esterno c\'è una cartella chiamata VENTOTENE con quattromiladuecento file, tre copie in tre posti diversi, e un file di testo con una riga: <i>"se lo trovate voi, la banda sta sopra il braccio di mare tra le due isole."</i> Non è indirizzata a nessuno. È indirizzata a chiunque, che è una cosa diversa e più coraggiosa.' },
  { flag: 'foto_cancellate',   icon: '📵', text: 'Una notte di febbraio, alle quattro e dieci, una donna si è messa a sedere nel letto e ha chiesto una cosa. Un uomo ha allungato la mano verso il telefono per aprire una cartella che non esiste più e si è fermato a mezz\'aria. Dormono ancora tutte le notti nella stessa stanza, e quel mezzo metro di buio è la cosa più abitata della casa.' },
  { flag: 'nome_sul_registro', icon: '📓', text: 'Nel registro dei passeggeri di una corsa Ventotene-Formia del 30 agosto 2026 c\'è una riga completata a mano, con una penna diversa da quella dell\'ufficio. La compagnia non archivia i registri per più di cinque anni. Quello lì, per qualche motivo, non è stato buttato.' },
  { flag: 'ciro_di_guardia',   icon: '📞', text: 'Un vecchio pescatore tiene nella tasca della cerata un foglietto piegato in quattro con un numero di terraferma e una regola scritta da un altro: <i>"se sente la corda, chiami. Non risponda: chiami me."</i> Ha chiamato quattro volte in nove anni. Ogni volta, dall\'altra parte, qualcuno ha risposto al primo squillo.' },
  { flag: 'ninnananna_lasciata', icon: '🍼', text: 'Sull\'isola, adesso, la seconda strofa la sanno in tre. Una la canta ai nipoti senza dire da dove viene, e i nipoti la trovano bruttissima e la imparano comunque, come si imparano tutte le canzoni delle nonne. Fra sessant\'anni, se qualcuno la sentirà da sotto, saprà rispondere.' },
  { flag: 'bagno_nel_perimetro', icon: '🏖', text: 'Davanti alla bocca del porto, dove c\'è la gente e i bambini urlano a due metri dall\'acqua, non c\'è mai stato niente e non ci sarà mai niente. Ci sono due persone che lo sanno per certo, e che d\'estate, in mezzo alla confusione più fastidiosa del Tirreno, fanno il bagno più tranquillo della loro vita.' },
  { flag: 'loop_infinito',     icon: '♾', text: 'Alle Parracine, nella stanza con la terrazza, il foglietto attaccato allo specchio col nastro ha una riga in più ogni volta che qualcuno lo guarda. Grafia larga, vocali tonde, di quelle dei filmati dell\'Istituto Luce. La prima riga nuova diceva soltanto: <b>anche voi</b>.' },
  /* ---- LE ULTIME SCELTE, che prima non lasciavano traccia ----
     Diciannove righe scritte in blocco il 24 agosto 2026, e la ragione e' una sola: lo
     strumento dei flag orfani ha detto che diciotto delle scelte FINALI del gioco — le
     ultime che il giocatore prende, quelle su cui sta di piu' a pensare — impostavano un
     flag che non leggeva nessuno e andavano nella stessa scena delle altre. Cioe' non
     cambiavano niente. La CRONACA e' esattamente il posto che serviva e c'era gia': non
     racconta di nuovo il finale, racconta cosa e' rimasto acceso altrove per colpa loro. */
  { flag: 'accettato',        icon: '🎫', text: 'A Formia, all\'ufficio della compagnia, chi è tornato ha chiesto di cambiare il ritorno da due passeggeri a uno. L\'impiegata ha fatto la domanda che deve fare — «il secondo rinuncia?» — e ha aspettato la risposta col dito sul tasto. La risposta è arrivata dopo undici secondi. Lei non ha alzato gli occhi, e questa è stata la cosa più gentile che le riusciva.' },
  { flag: 'cantato_insieme',  icon: '🎼', text: 'Sopra la franata, oltre la boa gialla, un idrofono comprato su internet registra da due anni la stessa cosa: un brusio, e dentro il brusio <b>due note che si rispondono</b>. Chi le ha registrate le ha mandate a un forum di bioacustica. Gli hanno risposto che sono due individui della stessa specie, probabilmente una coppia, e che quel tipo di richiamo serve a non perdersi.' },
  { flag: 'detta_ninnananna', icon: '🌙', text: 'Sul ponte di poppa c\'era una signora di Ponza che tornava dalla figlia. Ha sentito due strofe e una l\'ha riconosciuta: gliela cantava sua nonna e non se la ricordava intera. È scesa a Ponza con la seconda strofa in testa, e adesso la canta a un nipote che non ha paura dell\'acqua. Non ha mai saputo a chi doveva dire grazie.' },
  { flag: 'detta_sesta',      icon: '🕳', text: 'Un\'impresa di Formia, incaricata di un sondaggio per una condotta nuova, ha fermato la trivella a undici metri sotto l\'orto dei Coraggio perché è entrata nel vuoto. Il capocantiere ha scritto sul rapporto «cavità antropica non censita» e ha chiesto per iscritto di essere spostato su un altro cantiere. Gliel\'hanno concesso senza discutere, che nei cantieri non capita mai.' },
  { flag: 'detto_i_piani',    icon: '📋', text: 'In una tesi discussa a Napoli in marzo, a pagina ottantaquattro, c\'è una nota che cita tre nomi trovati in un carteggio del Ministero: <i>inferno, purgatorio, paradiso</i>. Il relatore ha chiesto di attenuare, che così sembra letteratura. La studentessa ha lasciato la nota e ci ha aggiunto la segnatura d\'archivio. Ha preso centodieci.' },
  { flag: 'detto_sperduto',   icon: '🙏', text: 'A bordo, quel pomeriggio, un marinaio di coperta ha sentito un nome e un\'ora e ha pensato che fosse un morto di famiglia. Ha fatto quello che si fa: si è toccato la fronte e ha detto «riposa». Non sapeva niente di niente — e per come funzionano queste cose è stata l\'unica preghiera che quell\'uomo abbia ricevuto in sessantun anni.' },
  { flag: 'fedi_a_chi_resta', icon: '💍', text: 'Alle Parracine, d\'inverno, c\'è una persona che dorme con due fedi legate a un filo di nylon appese al collo. Ada, che in ottant\'anni ha visto tutto, non ha fatto domande: ha solo detto che il nylon taglia, e le ha dato un cordino di cotone. Il cambio si è fatto in cucina, in silenzio, e nessuna delle due si è girata.' },
  { flag: 'nome_chiamato',    icon: '📄', text: 'Il verbale dell\'immersione, compilato al rientro perché così vuole la legge, ha una riga per le note. Chi l\'ha compilato ci ha scritto una cosa che non è una nota tecnica e che nessuno ha cancellato: <i>«ha sentito la corrente prima di me, come sempre»</i>. La copia sta in un faldone della Capitaneria di Formia, e ci resterà finché resta in piedi l\'edificio.' },
  { flag: 'nome_ripetuto',    icon: '📆', text: 'Non è finita in nessun archivio e non l\'ha sentita nessuno. Ma in un ufficio dove si progettano satelliti, ogni 2 settembre, un ingegnere si prende il pomeriggio e non dice perché. I permessi lì si approvano con un clic e non li legge nessuno: la data la sa solo lui, e va bene così.' },
  { flag: 'pagina_per_ada',   icon: '✉️', text: 'Ada ha ricevuto una busta con dentro un foglio scritto a mano da una parte sola. L\'ha letto in cucina, in piedi, col cappotto ancora addosso. Poi l\'ha piegato in quattro e l\'ha messo nel libro delle ricette, alla pagina della pasta e fagioli, che è quella che apre più spesso. Non ha risposto. A Natale è arrivato un pacco di taralli, e dentro non c\'era nessun biglietto perché non serviva.' },
  { flag: 'patto_del_silenzio', icon: '💾', text: 'Non risulta niente da nessuna parte, e questo era il patto. L\'unica traccia è una cartella su un disco esterno, chiamata con la data e nient\'altro, che viene ricopiata su un disco nuovo ogni tre o quattro anni perché i dischi muoiono e la cartella no. Non è stata più aperta dal 2026. Viene solo copiata.' },
  { flag: 'salito_da_solo',   icon: '☕', text: 'Il traghetto delle 17:30 del 30 agosto è partito con un passeggero in meno di quelli che aveva portato. Sul ponte di poppa, uno solo, in piedi, per due ore e un quarto, senza sedersi mai. Un marinaio gli ha portato un caffè a metà rotta senza che lo chiedesse, e non gliel\'ha fatto pagare: certi mestieri riconoscono certe facce.' },
  { flag: 'salutato_ciro',    icon: '🥫', text: 'Ciro non ha speso quei quaranta euro. Stanno in una scatola di latta insieme all\'orologio di suo padre e a una fotografia del 1965 in cui lui ha undici anni ed è sul molo. Alla nipote che gli ha chiesto perché non li spende ha risposto che non sono soldi: <b>è una ricevuta</b>.' },
  { flag: 'sesta_salutata',   icon: '🛣', text: 'Nel parcheggio dei motorini, sopra la sesta, il Comune ha rifatto l\'asfalto a novembre. Gli operai hanno notato che in un punto di tre metri per tre il bitume caldo si raffreddava più in fretta, e hanno dato una seconda passata. Sul rapporto non c\'è scritto niente: si è data la seconda passata e si è andati a casa.' },
  { flag: 'silenzio_su_come', icon: '🤐', text: 'Alla domanda «e com\'è andata a Ventotene?», che arriva sempre, la risposta è: «bello. C\'è un porto scavato nella roccia». È vero, è breve, e chiude il discorso. Viene detta così bene che nessuno l\'ha mai richiesta una seconda volta — e questa è la parte che certe notti non lascia dormire.' },
  { flag: 'terza_riga_incisa', icon: '⛏', text: 'Nella cisterna murata, a settanta centimetri da terra, sotto le due righe incise col coltellino ce n\'è una terza. È più profonda delle altre due perché chi l\'ha fatta, quella volta, aveva tempo. Dice quattro parole e <b>una data che non è ancora arrivata</b>.' },
  { flag: 'valigie_chiuse',   icon: '💨', text: 'Alle Parracine, nell\'armadio della stanza con la terrazza, c\'è un phon che non è di Ada. Lei l\'ha lasciato lì. Quando arriva qualcuno e chiede se c\'è il phon, risponde che sì e va a prenderlo — e ogni volta, mentre lo prende, si ferma un secondo con la mano sull\'anta.' },
  { flag: 'verita_pubblica',  icon: '🗂', text: 'Il Comune di Ventotene ha protocollato in ottobre un esposto di undici pagine con allegati fotografici, firmato, con indirizzo. È stato trasmesso per competenza alla Soprintendenza, che l\'ha trasmesso per competenza alla Capitaneria, che l\'ha trasmesso per competenza al Comune. Il fascicolo esiste, ha un numero, e il numero si può chiedere. Non l\'ha mai chiesto nessuno.' },
  { flag: 'file_stiva_tenuto', icon: '📼', text: 'Tre copie, come sempre: una sul telefono, una sul disco, una su un servizio che costa due euro al mese. Il video dura quattro minuti e undici, ed è stato guardato in tutto sei volte da una persona sola. Alla sesta, quella persona ha misurato una cosa con un righello sullo schermo, ha scritto un numero su un foglietto, e poi ha strappato il foglietto senza dirlo a nessuno.' },
  { flag: 'fossa_rispettata', icon: '🤚', text: 'Nel cimitero dei detenuti di Santo Stefano, nell\'angolo di nord-est, c\'è un avvallamento su cui l\'erba cresce grassa e verde e non l\'ha aperto nessuno. Nel 2029 un rilievo con il georadar l\'ha segnato come «anomalia» su una carta, e la carta è finita in un faldone. Chi l\'ha vista ha scritto una nota: <i>«scavo non urgente»</i>. Non lo era, e non lo è.' },
  { flag: 'nastro_a_meta',    icon: '⏹', text: 'In una scatola da scarpe, in fondo a un armadio, c\'è un registratore Geloso con dentro una cassetta ferma a metà: la banda è tesa, la bobina di destra è mezza piena, e nessuno l\'ha più mossa. Chi ce l\'ha messa sa esattamente quanti minuti di nastro non ha ascoltato — undici e quaranta — e non è un numero che ha bisogno di controllare, perché ci pensa da solo.' },
  { flag: 'cassetta_a_ciro',  icon: '📻', text: 'Al terzo pontile, dentro una borsa di tela con dentro le sigarette e una chiave inglese, c\'è una custodia di plastica trasparente con una cassetta senza etichetta. Ciro se la porta appresso in barca ogni giorno. Alla nipote che gliel\'ha chiesto ha detto che è musica. Non è musica, e non è nemmeno una bugia: è una cosa che va tenuta in compagnia.' },
  { flag: 'verita_coi_numeri', icon: '📐', text: 'In un ufficio dove si progettano satelliti c\'è una regola nuova che vale su una persona sola e nessuno sa da dove viene: quando c\'è da dire una cosa che pesa, prima si dice la cosa e POI si aprono i dati. L\'ha imposta a se stesso e la sbaglia ancora, circa una volta su tre. Circa: il numero se l\'è contato, e poi ha capito che contarlo era esattamente il problema.' },
  { flag: 'moduli_compilati', icon: '📋', text: 'Al diving del porto, in una cartella a molla dietro il bancone, ci sono due schede d\'immersione compilate in stampatello e mai firmate, con la data del 30 agosto 2026 e un timbro al posto della firma. Ogni primavera, quando si riordina, qualcuno le trova e le mette in fondo invece di buttarle. Nessuno lo ha deciso e nessuno se lo dice: si mettono in fondo.' },
  { flag: 'pratica_aperta',   icon: '🗄', text: 'Da qualche parte c\'è una riga che comincia con «del trenta agosto risulta» e finisce a metà, sul bianco, perché il dato non è mai arrivato. Non è un fascicolo che si può chiudere e non è un fascicolo che si può archiviare: sta in mezzo, come stanno le pratiche in mezzo, e ogni tanto qualcuno la rimette sopra la pila senza guardarla. Le due persone che avrebbero potuto completarla hanno detto un altro nome.' },
];
